/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e4e2df",
        "on-tertiary-fixed-variant": "#5c430a",
        "on-tertiary-container": "#4e3700",
        "on-primary-fixed-variant": "#5d4201",
        "on-secondary-fixed-variant": "#474746",
        "primary-fixed": "#ffdea5",
        "on-secondary-fixed": "#1c1b1b",
        outline: "#7f7667",
        "on-primary-container": "#4e3700",
        "tertiary-fixed-dim": "#e6c17e",
        "on-primary-fixed": "#261900",
        "inverse-primary": "#e9c176",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#e9c176",
        "surface-variant": "#e4e2df",
        "surface-container-low": "#f5f3f0",
        "outline-variant": "#d1c5b4",
        "surface-container-high": "#eae8e5",
        "inverse-on-surface": "#f2f0ed",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        tertiary: "#765a21",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdea5",
        "on-surface-variant": "#4e4639",
        "secondary-container": "#e2dfde",
        secondary: "#5f5e5e",
        "surface-tint": "#775a19",
        "on-background": "#1b1c1a",
        "secondary-fixed": "#e5e2e1",
        "on-surface": "#1b1c1a",
        primary: "#775a19",
        "tertiary-container": "#c3a060",
        "on-tertiary-fixed": "#271900",
        "surface-bright": "#fbf9f6",
        "surface-dim": "#dbdad7",
        "secondary-fixed-dim": "#c8c6c5",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#636262",
        "inverse-surface": "#30312f",
        "primary-container": "#c5a059",
        "surface-container": "#efeeeb",
        background: "#fbf9f6",
        surface: "#fbf9f6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-desktop": "3.5rem",
        "space-4xl": "6rem",
        "space-xs": "0.5rem",
        "container-padding-mobile": "1.25rem",
        "space-xxs": "0.25rem",
        "space-2xl": "3rem",
        "space-xl": "2rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-sm": "0.75rem",
        "space-3xl": "4rem",
      },
      fontFamily: {
        "display-hero": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-editorial": ["Playfair Display", "serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Playfair Display", "serif"],
        caption: ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "title-editorial": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.12em", fontWeight: "600" }],
        "display-hero-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.01em", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
